[package]
name = "continued_testing"
version = "0.1.0"
authors = ["layonthehorn <thomaspdressel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
text_io = "0.1.8"
termcolor = "1.1.0"
anyhow = "1.0.32"